server {
  listen 80;
  server_name ilyahost.sytes.net;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000;
  }
  location /static/ {
    alias /staticfiles/static/;
  }
  location / {
    alias /staticfiles/;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}